services:
  - type: web
    name: jawwak-google-flights
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: JAWAKK_GOOGLE_FLIGHTS_API_KEY
        sync: false
